import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Quintessential, Sen } from "next/font/google";
import "./globals.css";
import { Lenis } from "@/lib/Lenis";
import { Cursor } from "@/lib/Cursor";
import GSAP from "@/lib/GSAP";
import { Header } from "@/components/layouts/Header";
import Transition from "@/components/animations/Transition";
import Preloader from "@/components/animations/Preloader";
import { Footer } from "@/components/layouts/Footer";

const sen = Sen({
  variable: "--font-sans",
  subsets: ["latin"],
});

const quintessential = Quintessential({
  variable: "--font-cursive",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-dvh">
      <body
        className={`${sen.variable} ${quintessential.variable} antialiased min-h-dvh pt-16`}
      >
        <NuqsAdapter>
          <Preloader />
          <Header />
          <Transition>
            <Lenis>
              <Cursor />
              <GSAP />
              {children}
              <Footer />
            </Lenis>
          </Transition>
        </NuqsAdapter>
      </body>
    </html>
  );
}
